language: node_js
node_js:
  - node
cache:
  directories:
    - node_modules
script: 
  - npm i -g serverless
  - tsc
  - rm -r dist/
deploy:
  - provider: script
    script: npm run deploy
    on:
      branch: master

